### PR TITLE
Add How To

### PR DESCRIPTION
**Pull request by mave1993**
Hey, can you add a how to for windows, how to pack changed images? Regards

### CODE REVIEW

**Comment by bigunclemax** [comment]
Hi, here is new readme. You may ask if something is not clear.
https://github.com/bigunclemax/FTools/blob/win_release_0.3/README.md

**Comment by mave1993** [comment]
C:\Users\Patrick Hassmann\Desktop\FOCUS IPC Tool>imgunpkr -p -c export_list.csv -o ./dest_dir original_images.vbf
VBF file not found


renamed F1ET-14C026-BCC.vbf to original_images.vbf - shuld be a bug.

**Comment by mave1993** [comment]
C:\Users\Patrick Hassmann\Desktop\FOCUS IPC Tool\original_images.vbf
there is vbf stored.

**Comment by mave1993** [comment]
contact me please @ mave1993@hotmail.de - lets write a little bit. have some info and tool for you mate

**Pull request closed without merging**
